<?php

namespace WPMCP\Tools\Export;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Read-only listing of the WXR export files generated by export-content.
 * Does not mutate the site.
 */
class List_Exports
{
    public function handle(array $args): array
    {
        $dir = Export_Dir::path();
        if (! is_dir($dir)) {
            return ['exports' => []];
        }

        $entries = array_diff((array) scandir($dir), ['.', '..', '.htaccess', 'index.php']);

        $rows = [];
        foreach ($entries as $entry) {
            $path = trailingslashit($dir) . $entry;
            if (! is_file($path)) {
                continue;
            }
            $rows[] = [
                'name'    => $entry,
                'size'    => filesize($path),
                'created' => gmdate('Y-m-d H:i:s', (int) filemtime($path)),
            ];
        }

        usort($rows, static fn($a, $b) => strcmp($b['created'], $a['created']));

        return ['exports' => $rows];
    }
}
